remote_theme: hydecorp/hydejack # Changing theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Tammy Hartline's E-Portfolio]
description: [Portfolio to demonstrate my capabilities in various computer science techniques.]
